name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # выполняется ежедневно в 12:00 UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: Laynexx-ns/Laynexx-ns
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          TARGET_BRANCH: main
          TARGET_PATH: README.md
